### ISSUE TITLE
Inability to declare conversion rules on superclasses

### ISSUE THREAD

**Issue by dwt** [zopefoundation/zodbupdate#16]
Hi there,

yesterday we noticed that it is not possible to declare a conversion rule once for a class that has an instance variable, but that it instead has to be declared for all subclasses that inherit from that class that are actually in the the pickle.

On the one hand this makes sense as the tool (at that stage) doesn't know anything about the classes, doesn't instantiate them and just works on them, but on the other hand the projects where those classes are defined need to be installed so the rules can be found via the entry points defined in those projects.

In principle it would thus be possible to look at the MRO of all loadable classes and push down all the conversion rules from all the superclasses to all their leaf classes that are found.

However, even if this is not done, it should be documented that you need to push down these annotations to all the leaf classes that are actually reference in the pickle files for them to work. (I'm working on a pull request for this currently)

**Comment by mgedmin** [comment]
This is now [documented](https://github.com/zopefoundation/zodbupdate/commit/3aa97f0a0744497cd68941b4e9b5e18f268cd1a6), so should this issue be closed?

**Comment by dwt** [comment]
yes, closing this now.
