### ISSUE TITLE
Running with RelStorage?

### ISSUE THREAD

**Issue by tflorac** [zopefoundation/zodbupdate#28]
Hi,
I've tested zodbupdate (1.0.0 and 1.4.0) on a database using RelStorage 3.0.1.
But I get an exception when running:
```
Loaded 3 rename rules from pyams_site.generations:renames
Loaded 2 rename rules from pyams_catalog.generations:renames
An error occured
Traceback (most recent call last):
  File "/var/local/env/pycharm/lib/python3.5/site-packages/zodbupdate/main.py", line 186, in main
    updater()
  File "/var/local/env/pycharm/lib/python3.5/site-packages/zodbupdate/update.py", line 97, in __call__
    raise error
  File "/var/local/env/pycharm/lib/python3.5/site-packages/zodbupdate/update.py", line 74, in __call__
    for oid, serial, current in self.records:
  File "/var/local/env/pycharm/lib/python3.5/site-packages/zodbupdate/update.py", line 140, in records
    not self.storage.supportsUndo()):
AttributeError: 'RelStorage' object has no attribute 'supportsUndo'
Stopped processing, due to: 'RelStorage' object has no attribute 'supportsUndo'
```

So is there a way to update a RelStorage database without converting it back and forth into a classic FileStorage?

Best regards,
Thierry

**Comment by jamadden** [comment]
Cross ref: https://github.com/zodb/relstorage/issues/388#issuecomment-562553376

> `supportsUndo` is a method of [IStorageUndoable](https://zodb.readthedocs.io/en/latest/api.html#ZODB.interfaces.IStorageUndoable). RelStorage only implements `IStorageUndoable` when `keep-history` is true. It seems that zodbupdate always assumes that method is available; it should be checking whether `IStorageUndoable.providedBy(self.storage)`. It looks like the full test should be 
```python
elif (IStorageIteration.providedBy(storage) 
         and (not IStorageUndoable.providedBy(self.storage) 
              or not storage.supportsUndo())):
   …

```

**Comment by icemac** [comment]
Can this issue be closed as there is #29 which seem to fix it.
Is there still something open here?

**Comment by jamadden** [comment]
I would say that RelStorage can't be considered to work until it's tested on CI, which is what #30 is about. Fixing #30 would also fix this. But one could have a more narrow interpretation and consider this exact issue fix.

**Comment by icemac** [comment]
As there is #30 as a followup and as @tflorac seems to be happy with the implementation, I am going to close this issue.
Thank you.
